# Spring properties
spring:
  application:
     name: product-service
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ice-product
  jpa:
    hibernate:
      ddl-auto: update

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port