# Spring properties
spring:
  application:
     name: quote-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port


# service name bindings
productService:
  url: product-service